name: heat_care_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"  # Formato correto para restrição de versão

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/heatcarelogo.png  # Note que o nome do arquivo está em minúsculas
    - assets/sun.png
    - assets/cold.png
    - assets/tshirt.png
    - assets/block.png
    - assets/drop.png
    - assets/sofa.png
    - assets/telephone.png